import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
import numpy as np
import time

# Sample data related to rockets
rocket_data = [
   "Interplanetary travel requires advanced rocket propulsion systems.",
    "Rocket scientists analyze data from telemetry to improve launch success rates.",
    "SpaceX's Starship aims to revolutionize space travel with its fully reusable design.",
    "The concept of space debris tracking is crucial for preventing collisions with active satellites and rockets.",
    "NASA's Mars rovers, including Opportunity and Spirit, paved the way for scientific discoveries on the Red Planet.",
    "Rocket launches from the Vandenberg Space Force Base contribute to a range of polar orbit missions.",
    "The concept of nuclear-powered rockets is explored for potential deep-space missions.",
    "SpaceX's Crew Dragon is a crewed spacecraft designed for missions to the International Space Station.",
    "The Bezos-backed Blue Origin focuses on developing reusable rocket technologies.",
    "Satellite constellations, like Starlink by SpaceX, aim to provide global internet coverage using rocket launches.",
    "The concept of a space race in the 21st century involves private companies competing for space exploration milestones.",
    "Ion thrusters, common in satellite propulsion, provide efficient and low-thrust maneuvers in space.",
    "The study of space geology involves analyzing rocks and minerals found on other celestial bodies.",
    "Rocket launch weather forecasts are crucial for ensuring safe and successful missions.",
    "The Artemis program plans to land the first woman and the next man on the Moon using the Space Launch System.",
    "Microgravity research on rockets contributes to understanding its effects on biological organisms.",
    "The dream of interstellar travel involves developing rockets capable of reaching other star systems.",
    "Rocket landing platforms at sea, like SpaceX's drone ships, enable reusable rocket stages to return safely.",
    "International partnerships, such as the ISS collaboration, showcase diplomatic efforts in space exploration.",
    "CubeSats are small, cube-shaped satellites often launched as secondary payloads on rockets.",
    "Rocket fairing recovery aims to reduce space debris by retrieving the protective shells after launch.",
    "The concept of space farming explores growing crops on spacecraft and other celestial bodies.",
    "Hybrid rocket engines, combining liquid and solid propulsion, offer advantages in safety and simplicity.",
    "NASA's Perseverance rover, launched by the Mars 2020 mission, searches for signs of past microbial life.",
    "SpaceX's Falcon 9 rocket is a workhorse for launching satellites, cargo, and crewed missions.",
    "Astrophysicists use data from rocket-borne instruments to study cosmic phenomena beyond Earth's atmosphere.",
    "Rocket ignition systems play a critical role in the reliable and timely start of rocket engines.",
    "The concept of a space bus involves a reusable spacecraft that shuttles between Earth and orbiting space stations.",
    "Rocket launch countdowns involve a sequence of carefully timed events leading up to liftoff.",
    "The study of space habitats explores sustainable living solutions for long-duration space missions.",
    "In-space manufacturing using 3D printers transported by rockets opens new possibilities for construction in orbit.",
    "Rocket engines using green propellants aim to minimize environmental impact during space travel.",
    "Space agencies use sounding rockets for scientific experiments in the upper atmosphere and ionosphere.",
    "The concept of a space telescope constellation involves multiple telescopes working together for enhanced observations.",
    "Rocket launches contribute to international efforts to monitor climate change and environmental conditions.",
    "The Space Launch System's powerful boosters provide the thrust needed for deep-space missions beyond Earth's orbit.",
    "Space tourism companies offer suborbital flights, allowing civilians to experience the sensation of weightlessness.",
    "Rocket-based exploration of ocean worlds, like Europa and Titan, aims to uncover secrets beneath their icy surfaces.",
    "Asteroid deflection missions using rockets are proposed to mitigate potential threats to Earth from near-Earth objects.",
    "Rocket-powered landers are essential for safely delivering payloads to the surfaces of other planets and moons.",
    "SpaceX's Super Heavy rocket, under development, is intended to carry heavy payloads for interplanetary missions.",
    "The concept of a space zoo involves transporting animals into orbit for scientific studies on the effects of microgravity.",
    "Rocket engine failures are meticulously studied to improve safety measures and prevent recurrence.",
    "SpaceX's Crew Dragon Demo-2 marked the first crewed orbital launch by a private company.",
    "The study of celestial mechanics helps optimize rocket trajectories for efficient space travel.",
    "Rocket payload separation mechanisms ensure that satellites and instruments are deployed at the correct orbital positions.",
    "The concept of a space train envisions interconnected spacecraft shuttling between Earth, the Moon, and Mars.",
    "Rocket launch pollution studies aim to understand and minimize the environmental impact of space missions.",
    "The study of space sociology explores the dynamics of human societies living in confined spacecraft environments.",
    "The concept of a space marathon involves running in simulated low-gravity environments aboard spacecraft.",
    "Rocket stages left in orbit may contribute to space debris, and efforts are made to deorbit or control their trajectories.",
    "SpaceX's Starlink mega-constellation, consisting of thousands of satellites, aims to provide global broadband internet coverage.",
    "The concept of space insurance involves assessing risks and providing coverage for satellite launches and space missions.",
    "Rocket engine gimbal systems allow for precise control of the rocket's orientation during flight.",
    "Space agencies collaborate on international space law to regulate activities and prevent conflicts in outer space.",
    "Rocket-based studies of cosmic rays contribute to understanding high-energy particles from distant astrophysical sources.",
    "The concept of a space newspaper involves transmitting news and updates to space stations and interplanetary outposts.",
    "Rocket-powered space probes, like Voyager 1 and 2, continue to send data from the outer reaches of the solar system.",
    "SpaceX's Mars colonization plans aim to establish a self-sustaining human settlement on the Red Planet.",
    "Rocket launch tourism offers enthusiasts the opportunity to witness live rocket launches from spaceports around the world.",
    "The concept of a space high-speed rail involves magnetically propelled spacecraft for rapid transport between celestial bodies.",
    "Rocket engine health monitoring systems provide real-time data to ensure safe and reliable operation.",
    "Space agencies study the effects of microgravity on human health to prepare for long-duration missions beyond Earth.",
    "Rocket-powered deep-space missions explore the outer reaches of the solar system and beyond.",
    "The concept of a space time capsule involves sending messages and artifacts to distant star systems for potential extraterrestrial discovery.",
    "Rocket-powered spacewalks enable astronauts to repair and maintain spacecraft in the harsh conditions of outer space.",
    "SpaceX's plans for a crewed mission around the Moon involve the Starship spacecraft and the Space Launch System.",
    "Rocket-based exploration of the Sun involves launching solar observatories to study solar activity and phenomena.",
    "The concept of a space theme park involves recreating the experience of space travel through simulated rocket rides and exhibits.",
    "Rocket-powered space drones are proposed for exploring the atmospheres of other planets and moons.",
    "Space agencies collaborate on space traffic management to avoid collisions and congestion in Earth's orbit.",
    "Rocket engine acoustic studies aim to minimize the noise produced during launches for environmental and safety reasons.",
    "Rockets are powerful machines that can travel into space.",
    "NASA has launched numerous rockets to explore the cosmos.",
    "Rocket propulsion relies on the principle of Newton's third law.",
    "Elon Musk's SpaceX company is known for developing reusable rockets.",
    "The Apollo program achieved historic moon landings using powerful rockets.",
    "Rocket science involves complex engineering and physics principles.",
    "Saturn V was a powerful rocket used in the Apollo missions.",
    "The Falcon Heavy, developed by SpaceX, is one of the most powerful operational rockets.",
    "Rocket engines use thrust to overcome Earth's gravitational pull during launch.",
    "The Hubble Space Telescope was carried into orbit by the Space Shuttle Discovery's rocket.",
    "Rocket technology has evolved significantly since the early days of space exploration.",
    "The International Space Station is resupplied by cargo rockets at regular intervals.",
    "Rocket launches are meticulously planned events with precise timing and coordination.",
    "The concept of multistage rockets allows for more efficient use of fuel during space travel.",
    "Rocket testing is a crucial step in ensuring the reliability and safety of space missions.",
    "Commercial companies, along with government agencies, are actively involved in rocket development.",
    "Advancements in materials science contribute to the design of lighter and more efficient rocket components.",
    "The Vega rocket, developed by the European Space Agency, is designed for small satellite launches.",
    "The James Webb Space Telescope was transported to its destination using an Ariane 5 rocket.",
    "Rocket payloads include satellites, scientific instruments, and sometimes even human explorers.",
    "SpaceX's Starship is a next-generation fully reusable spacecraft intended for interplanetary travel.",
    "Rocket launches can be viewed by the public at designated sites, providing a unique and awe-inspiring experience.",
    "Space agencies collaborate globally to share knowledge and resources for peaceful space exploration.",
    "The Delta IV Heavy is another example of a powerful rocket used for various space missions.",
    "Rocket failures are meticulously analyzed to improve safety and reliability in future launches.",
    "The concept of orbital mechanics is fundamental to understanding how rockets navigate in space.",
    "Reusable rocket technology has the potential to significantly reduce the cost of space exploration.",
    "The SLS (Space Launch System) is NASA's next-generation rocket designed for deep-space missions.",
    "In-space propulsion systems are used to maneuver satellites and spacecraft after they reach orbit.",
    "The development of ion propulsion systems represents a leap forward in fuel efficiency for long-duration space missions.",
    "The concept of rocketry dates back to ancient China, where gunpowder-filled tubes were used for propulsion.",
    "The X-15 rocket plane set numerous speed and altitude records during the early days of spaceflight research.",
    "Space agencies continuously explore innovative propulsion technologies for future missions.",
    "Rocket fuel is carefully selected based on the specific requirements and conditions of each mission.",
    "The concept of space elevators, though theoretical, presents an intriguing alternative to traditional rocket launches.",
    "Mars rovers, such as Curiosity and Perseverance, were transported to the Red Planet by specialized landing rockets.",
    "The study of astrodynamics is essential for predicting and optimizing the trajectories of rockets in space.",
    "Rocketry has played a pivotal role in advancing our understanding of the universe and our place in it.",
    "The concept of space tourism envisions rockets carrying civilians on suborbital or orbital journeys.",
    "The New Shepard rocket, developed by Blue Origin, is designed for suborbital space tourism.",
    "Rocket stages are carefully jettisoned during flight to optimize the efficiency of the overall launch.",
    "The concept of a space race between nations fueled significant advancements in rocket technology during the mid-20th century.",
    "Rocketry enthusiasts often participate in amateur rocket launches, showcasing creativity and technical skill.",
    "The Space Launch System's powerful engines generate thrust equivalent to multiple jet engines combined.",
    "Rocket fairings are protective shells that shield payloads from aerodynamic forces during the initial phases of launch.",
    "The study of exoplanets relies on telescopes carried into space by rockets to observe distant planetary systems.",
    "The concept of interplanetary colonization raises ethical and logistical questions related to rocket-based space travel.",
    "In-space refueling technologies are being explored as a means to extend the operational life of satellites and spacecraft.",
    "Rocket design considers factors such as aerodynamics, structural integrity, and thermal management for successful missions.",
    "The concept of a space elevator, if realized, could revolutionize the way payloads are transported from Earth to space.",
    "Rocket launches from different launch sites around the world contribute to the global effort of space exploration.",
    "The study of space weather involves monitoring the effects of solar activity on rockets and satellites in Earth's orbit.",
    "The concept of nuclear thermal propulsion presents a potential solution for faster and more efficient deep-space travel.",
    "Rocket payload adapters are customized to securely attach and deploy various types of payloads during space missions.",
    "The concept of asteroid mining envisions rockets extracting valuable resources from celestial bodies for use on Earth.",
    "Rocket design incorporates redundancy and fail-safes to ensure mission success even in the face of unexpected challenges.",
    "The concept of a spaceplane combines features of both aircraft and rockets for reusable and versatile space travel.",
    "Rocket scientists and engineers collaborate across disciplines to address the multifaceted challenges of space exploration.",
    "The concept of a lunar gateway involves using rockets to establish a human outpost in orbit around the Moon for future missions.",
    "Rocket launches are scheduled with precision, taking into account orbital mechanics and launch windows for optimal trajectories.",
    "The study of microgravity effects on materials and biological systems is conducted aboard rockets during parabolic flights.",
    "Rocket landing technologies, such as those employed by SpaceX's Falcon 9, enable reusable and cost-effective space travel.",
    "The concept of in-situ resource utilization explores the possibility of using resources from other celestial bodies to support space missions.",
    "Rocket scientists play a critical role in advancing our capabilities for exploring the far reaches of our solar system and beyond.",
    "The Artemis program aims to return humans to the Moon, utilizing powerful rockets for lunar exploration.",
    "Rocket trajectories are carefully calculated to ensure precise navigation through the vacuum of space.",
    "The concept of space-based solar power involves using rockets to deploy solar power satellites that beam energy to Earth.",
    "Rocket testing facilities are equipped with specialized infrastructure to simulate the extreme conditions of spaceflight.",
    "The study of space debris and orbital debris mitigation strategies is essential for maintaining the long-term sustainability of space activities.",
    "Rocket propulsion technologies, such as ion drives and solar sails, offer alternative methods for navigating the cosmos.",
    "The concept of a spacewalk involves astronauts using rockets on their spacesuits to maneuver in microgravity outside the spacecraft.",
    "Rocket launch sites, such as Cape Canaveral and Baikonur Cosmodrome, have witnessed historic moments in space exploration.",
    "The concept of a Mars colony envisions using rockets to transport settlers and supplies for the establishment of a human presence on the Red Planet.",
    "Rocket failure investigations contribute to the continuous improvement of safety protocols and engineering practices in the aerospace industry.",
    "The study of planetary defense involves exploring technologies, including rockets, to mitigate potential threats from near-Earth objects.",
    "Rocketry has inspired countless individuals to pursue careers in science, technology, engineering, and mathematics (STEM).",
    "The concept of a space hotel raises questions about the feasibility and logistics of using rockets for commercial space tourism.",
    "Rocket staging events involve the sequential firing and separation of rocket stages to optimize velocity during ascent.",
    "The study of gravitational assists involves using the gravitational pull of celestial bodies to enhance the trajectories and efficiency of rockets.",
    "Rocket payload fairings are aerodynamically shaped to minimize drag during the initial phase of a rocket's ascent.",
    "The concept of a space tug involves using specialized rockets to transport payloads between different orbits or celestial bodies.",
    "Rocket launches contribute to our understanding of Earth's atmosphere, including the dynamics of upper atmospheric layers.",
    "The study of space ecology explores the challenges and solutions related to sustaining life on long-duration space missions launched by rockets.",
    "Rocket-based space telescopes, such as the Hubble Space Telescope, provide invaluable insights into the distant reaches of the universe.",
    "The concept of a space-based manufacturing facility involves using rockets to transport equipment and materials for production in microgravity.",
    "Rocket nozzle designs are optimized to efficiently expel exhaust gases, maximizing thrust during the launch phase.",
    "The study of space law addresses legal considerations related to rocket launches, satellite operations, and international cooperation in space activities.",
    "Rocket trajectories are influenced by celestial bodies, magnetic fields, and other environmental factors encountered during space travel.",
    "The concept of a space capsule involves using rockets to transport crewed or uncrewed vehicles for reentry and landing on Earth.",
    "Rocket stages are often equipped with guidance systems to ensure accurate navigation and trajectory control throughout the launch.",
    "Rocket launches are broadcasted globally, allowing people around the world to witness the awe-inspiring spectacle of space exploration.",
    "The concept of a space colony envisions self-sustaining habitats established using rockets to transport essential resources and equipment.",
    "Rocket-based observations of celestial events, such as eclipses and transits, contribute to scientific understanding and public engagement in astronomy.",
    "The study of space medicine addresses the physiological and psychological challenges faced by astronauts during rocket launches and space missions.",
    "Rocket propellants are selected based on their chemical properties and performance characteristics to meet the specific requirements of each mission.",
    "The concept of a space agency involves national or international organizations coordinating and conducting rocket-based space exploration initiatives.",
    "Rocket testing includes both ground-based tests and in-flight tests to validate the performance and reliability of rocket systems.",
    "Rocket development timelines can span several years, involving research, design, testing, and iterative improvements to achieve mission success.",
    "The concept of space habitats explores the design and construction of living environments transported by rockets for long-term human presence in space.",
    "Rocket payloads, such as scientific instruments and communication satellites, contribute to advancements in technology and our understanding of the universe.",
    "Rocket launches serve as milestones in space history, marking achievements in science, exploration, and international collaboration.",
    "The study of space archaeology explores the remnants of past rocket launches and space activities to understand the cultural and historical significance of space exploration.",
    "Rocket engine technologies, including liquid propulsion and solid rocket boosters, are continuously refined to enhance performance and efficiency.",
    "The concept of space art involves using rockets to deploy art installations or projects that engage with the unique environment of outer space.",
    "Rocket launches from private space companies, in addition to government agencies, contribute to the growing accessibility of space for scientific, commercial, and educational purposes.",
    "The study of space psychology delves into the psychological effects of long-duration space travel, including the mental well-being of astronauts launched by rockets.",
    "Rocket payloads designed for space science experiments contribute to our understanding of fundamental physical principles and phenomena in the cosmos.",
    "The concept of a space concert envisions performances transmitted via rockets to space, reaching audiences beyond the confines of Earth.",
    "Rocket-based exploration of icy moons, such as Europa and Enceladus, aims to uncover potential habitable environments and signs of extraterrestrial life.",
    "Rocket launches are celebrated events that inspire wonder and curiosity, fostering a sense of shared humanity and collective aspirations for the future of space exploration."
        "Rocket launches play a vital role in advancing scientific knowledge and space exploration.",
    "The development of reusable rocket technology is a significant milestone in the aerospace industry.",
    "Rocket scientists continually innovate to enhance the efficiency and safety of space missions.",
    "Commercial space companies, like Virgin Galactic, contribute to the democratization of space travel.",
    "The study of rocketry encompasses a wide range of disciplines, including aerodynamics and thermodynamics.",
    "SpaceX's Starship is designed for ambitious missions, including crewed missions to Mars.",
    "The concept of a space telescope on the Moon is explored for clearer observations of distant celestial objects.",
    "Rocket propulsion systems vary, with some using liquid fuel and others utilizing solid propellants.",
    "Advancements in artificial intelligence play a role in optimizing rocket launch trajectories and operations.",
    "Rocket engine testing involves simulating extreme conditions to ensure reliability in actual space environments.",
    "Space agencies collaborate on projects like the Lunar Gateway to establish a sustainable human presence beyond Earth.",
    "Rocketry enthusiasts organize rocketry clubs and events to promote interest in space-related activities.",
    "The dream of space colonization involves rockets as the primary means of transporting settlers to distant planets.",
    "Astronauts undergo rigorous training to prepare for the physical and psychological challenges of rocket launches.",
    "The concept of a space university envisions educational institutions dedicated to space-related studies and research.",
    "Rocket payload design considers factors such as weight distribution, structural integrity, and thermal protection.",
    "The exploration of near-Earth asteroids involves rockets as vehicles for scientific observation and potential resource extraction.",
    "The Artemis program aims to land the first woman and the next man on the lunar South Pole by the mid-2020s.",
    "Rocket science fiction in literature and movies often inspires real-world innovations and technologies.",
    "The development of miniaturized rockets enables cost-effective launches for small satellites and research payloads.",
    "Rocket-powered space probes, like the Voyager spacecraft, continue their journeys into the interstellar medium.",
    "The concept of space debris removal involves using specialized rockets to clean up defunct satellites and fragments in orbit.",
    "Rocketry heritage includes pioneers like Robert H. Goddard, who laid the foundations for modern rocket science.",
    "The study of space exobiology explores the possibility of extraterrestrial life beyond Earth, motivating missions to Mars and beyond.",
    "Rocket fuel efficiency is a crucial aspect of space missions, influencing payload capacity and mission duration.",
    "The James Webb Space Telescope, set to launch on an Ariane 5 rocket, will revolutionize our understanding of the cosmos.",
    "Rocket scientists and engineers are essential contributors to international collaborations, such as the European Space Agency.",
    "The concept of a space academy involves training the next generation of astronauts, engineers, and scientists.",
    "Rocket stages left in orbit are monitored to prevent collisions with operational satellites and spacecraft.",
    "The study of rocket plasma dynamics contributes to understanding the behavior of ionized gases in space propulsion.",
    "Rocket-based cargo missions supply the International Space Station with essentials for scientific experiments and daily life.",
    "The concept of space art installations involves using rockets to deploy sculptures and visual displays in outer space.",
    "Rocket engine throttling capability allows for precise control of thrust during different phases of a space mission.",
    "Space agencies invest in research and development to create eco-friendly rocket propellants for sustainable space travel.",
    "Rocket navigation systems rely on celestial navigation techniques for accurate positioning in deep space.",
    "The concept of a space music festival explores the idea of hosting live musical performances in microgravity environments.",
    "Rocket payload integration facilities ensure the proper assembly and testing of satellite payloads before launch.",
    "The study of rocket vibrations and acoustics addresses challenges related to spacecraft integrity during the launch phase.",
    "The deployment of constellations of Earth-observing satellites aids in monitoring natural disasters and environmental changes.",
    "Rocket-powered space habitats are envisioned as self-contained environments for long-term human habitation in space.",
    "The concept of a space comedy show involves filming humorous content aboard spacecraft for entertainment purposes.",
    "Rocket stage recovery technologies, like SpaceX's fairing-catching ships, aim to reduce launch costs and environmental impact.",
    "Space agencies explore the possibility of utilizing lunar resources for rocket propellants and construction materials.",
    "Rocket launches contribute to inspiring future generations to pursue careers in STEM fields and space exploration.",
    "The concept of a space research outpost envisions a base on the Moon or Mars for scientific studies and exploration.",
    "Rocket payload adaptability allows for the launch of diverse payloads, including scientific instruments and communication satellites.",
    "The study of hypersonic rocket technology explores the potential for ultra-fast travel within Earth's atmosphere.",
    "Rocket engine design principles are influenced by the need for reliability, efficiency, and adaptability to various mission profiles.",
    "The development of rocket avionics involves advanced electronic systems for navigation, control, and communication.",
    "Space agencies prioritize international cooperation to share resources and expertise for joint space exploration missions.",
    "The concept of a space fashion show involves designing and showcasing clothing suitable for future space travelers.",
    "Rocket payload separation mechanisms are critical for ensuring the precise deployment of satellites and scientific instruments.",
    "The study of space archaeology involves preserving and studying artifacts from historic rocket launches and space missions.",
    "Rocket engine ignition technology is continuously improved for faster and more reliable engine start-ups.",
    "The concept of a space culinary experience explores the creation of gourmet meals in the unique conditions of space travel.",
    "Rocket launch safety protocols are developed to protect both the payload and the surrounding environment during liftoff.",
    "Space agencies consider the potential use of nuclear-powered rockets for faster and more efficient deep-space exploration.",
    "Rocket-powered space art installations use controlled bursts of propulsion to create dynamic visual displays in orbit.",
    "The study of rocket cryogenics involves handling and storing propellants at extremely low temperatures for optimal performance.",
    "The concept of a space wildlife sanctuary involves protecting celestial environments from human impact during space exploration.",
    "Rocket-powered sample return missions aim to collect and bring back extraterrestrial materials for scientific analysis on Earth.",
    "Space agencies invest in advanced rocket materials, including lightweight alloys and composites, for enhanced performance.",
    "The concept of a space documentary series involves producing educational content about space exploration and rocket science.",
    "Rocket launch operators coordinate with air traffic control to ensure the safe integration of rocket launches into airspace.",
    "The study of rocket plasma thrusters explores efficient methods of spacecraft propulsion using ionized gases.",
    "The concept of space disaster response involves utilizing rockets to deploy emergency supplies and support in times of crisis.",
    "Rocket engine gimbal technology allows for the precise control and adjustment of a rocket's direction during flight.",
    "Space agencies plan missions to study the atmospheres of distant planets and exoplanets using specialized rocket probes.",
    "The concept of a space ecosystem involves the interconnected relationships between living organisms and technology in space.",
    "Rocket-powered cargo missions deliver supplies and equipment to space stations, ensuring continuous scientific research.",
    "The development of lightweight and durable rocket fairings is crucial for protecting payloads during the launch phase.",
    "The study of rocket thermal protection systems addresses the challenges of reentry and high-temperature environments.",
    "The concept of a space-themed escape room involves creating interactive challenges in simulated spacecraft environments.",
    "Rocket engine combustion studies aim to optimize the efficiency of fuel burning for enhanced propulsion.",
    "Space agencies explore the potential use of nuclear thermal rockets for crewed missions to Mars and other distant destinations.",
    "The concept of a space laser communication network involves using lasers carried by rockets for high-speed data transmission.",
    "Rocket payload deployment strategies ensure that satellites and instruments are released into their intended orbits.",
    "The study of rocket plasma diagnostics involves analyzing the properties of ionized gases in space propulsion systems.",
    "The development of green rocket propellants focuses on environmentally friendly alternatives for space exploration.",
    "The concept of a space fashion design competition encourages creativity in designing apparel suitable for space travelers.",
    "Rocket engine health monitoring systems utilize sensors and data analysis for real-time diagnostics and safety.",
    "Space agencies collaborate on global initiatives to address space debris and orbital congestion for sustainable space activities.",
    "Rocket payloads for space tourism aim to provide civilians with unique and memorable experiences in microgravity.",
    "The concept of a space-inspired art gallery involves showcasing works created by artists inspired by space and rocketry.",
    "Rocket propulsion labs at universities contribute to the education and training of future generations of aerospace engineers.",
    "The study of rocket trajectory optimization involves mathematical models to determine the most efficient paths for space missions.",
    "The concept of a space-themed amusement park includes rides and attractions simulating the experience of space travel.",
    "Rocket engine nozzle designs are optimized for specific mission requirements, considering factors like thrust and efficiency.",
    "Space agencies coordinate satellite launches to create Earth observation constellations for comprehensive global coverage.",
    "The study of rocket combustion instability addresses challenges in maintaining stable and controlled burning of propellants.",
    "The concept of space robotic missions involves deploying robots to perform tasks in space, from repairs to scientific exploration.",
    "Rocket payload separation systems use pyrotechnics and mechanisms to release payloads at precise moments during a launch.",
    "The development of advanced rocket guidance systems enables accurate navigation through complex orbital trajectories.",
    "The concept of a space-themed virtual reality experience involves simulating space exploration missions for entertainment.",
    "Rocket propulsion innovations include the exploration of alternative propulsion methods, such as nuclear thermal rockets.",
    "Space agencies conduct experiments on the International Space Station using rockets to transport scientific payloads.",
    "The study of rocket turbulence modeling enhances our understanding of aerodynamic forces during spaceflight.",
    "The concept of a space-themed mobile app offers users interactive content and information about space exploration.",
    "Rocket engine nozzle cooling systems use advanced materials and engineering to withstand high-temperature conditions.",
    "Space agencies collaborate on interplanetary missions to study the atmospheres and surfaces of distant planets.",
    "Rocket payload integration engineers ensure the proper assembly and compatibility of various payloads for a successful launch.",
    "The study of rocket fluid dynamics investigates the behavior of liquids in microgravity, essential for fuel systems.",
    "The concept of a space-themed escape room involves creating interactive challenges in simulated spacecraft environments.",
    "Rocket engine combustion efficiency is crucial for optimizing fuel consumption and mission duration.",
    "Space agencies explore the potential of nuclear electric propulsion for efficient and sustained deep-space missions.",
    "The development of rocket stage separation mechanisms ensures the safe and precise jettisoning of spent rocket sections.",
    "Rocket payload fairings are designed to protect payloads from aerodynamic forces and environmental conditions during ascent.",
    "The concept of space-themed educational programs involves hands-on activities and projects related to rocket science.",
    "Rocket engine nozzle expansion ratios are optimized for different phases of a mission to maximize thrust.",
    "Space agencies collaborate on the study of space weather to understand its impact on satellites and space missions.",
    "The concept of a space-themed music album involves creating original compositions inspired by the wonders of the cosmos.",
    "Rocket engine testing facilities simulate extreme conditions, including vacuum and temperature variations, for comprehensive testing.",
    "The development of hybrid rocket engines combines the benefits of liquid and solid propulsion for versatile space missions.",
    "Space agencies work on establishing permanent lunar bases using rockets for transportation and logistics.",
    "Rocket engine thrust vectoring allows for controlled changes in the direction of thrust, enabling precise trajectory adjustments.",
    "The concept of a space-themed video game offers players virtual experiences of space exploration and rocket launches.",
    "Rocket payload separation mechanisms use reliable and redundant systems to ensure successful deployment in orbit.",
    "Space agencies conduct experiments on the effects of microgravity on plant growth and agriculture using rockets.",
    "The study of rocket radiation shielding is crucial for protecting astronauts from cosmic radiation during deep-space missions.",
    "The concept of space-themed literature includes novels and stories exploring the challenges and wonders of space travel.",
    "Rocket payload adapters are customized to accommodate various payload sizes and shapes for different launch vehicles.",
    "Rocket engine nozzle materials are selected for their durability and resistance to high-temperature combustion.",
    "Space agencies collaborate on international space exploration initiatives, fostering cooperation and shared resources.",
    "The concept of a space-themed podcast involves discussions and interviews with experts in the field of space exploration.",
    "Rocket launch operators coordinate with weather agencies to ensure safe launch conditions and minimize risks.",
    "The development of advanced rocket guidance algorithms improves the precision and efficiency of space missions.",
    "Rocket payload fairing jettisoning is a carefully timed event to reduce aerodynamic drag and optimize launch efficiency.",
    "The study of rocket engine plume dynamics examines the behavior of exhaust gases in various atmospheric conditions.",
    "The concept of space-themed fashion design competitions encourages innovation in creating space-inspired clothing.",
    "Rocket engine ignition systems use reliable and redundant mechanisms to ensure successful engine startup.",
    "Space agencies collaborate on space traffic management to avoid collisions and maintain order in Earth's orbit.",
    "Rocket engine acoustic studies contribute to minimizing noise pollution during launches for environmental and safety reasons.",
    "Rocket payload fairing recovery efforts focus on retrieving and reusing fairings to reduce space debris.",
    "The concept of a space-themed cooking show involves preparing meals in microgravity conditions for entertainment.",
    "Rocket engine health monitoring systems provide real-time data to ensure safe and reliable operation.",
    "Space agencies study the effects of microgravity on human health to prepare for long-duration missions beyond Earth.",
    "Rocket-powered deep-space missions explore the outer reaches of the solar system and beyond.",
    "The concept of a space time capsule involves sending messages and artifacts to distant star systems for potential extraterrestrial discovery.",
    "Rocket-powered spacewalks enable astronauts to repair and maintain spacecraft in the harsh conditions of outer space.",
    "SpaceX's plans for a crewed mission around the Moon involve the Starship spacecraft and the Space Launch System.",
    "Rocket-based exploration of the Sun involves launching solar observatories to study solar activity and phenomena.",
    "The concept of a space theme park involves recreating the experience of space travel through simulated rocket rides and exhibits.",
    "Rocket-powered space drones are proposed for exploring the atmospheres of other planets and moons.",
    "Space agencies collaborate on space traffic management to avoid collisions and congestion in Earth's orbit.",
    "Rocket engine acoustic studies aim to minimize the noise produced during launches for environmental and safety reasons.",
    "Rockets are powerful machines that can travel into space.",
    "NASA has launched numerous rockets to explore the cosmos.",
    "Rocket propulsion relies on the principle of Newton's third law.",
    "Elon Musk's SpaceX company is known for developing reusable rockets.",
]


# Tokenize the text data
tokenizer = tf.keras.preprocessing.text.Tokenizer()
tokenizer.fit_on_texts(rocket_data)
total_words = len(tokenizer.word_index) + 1

# Create input sequences and labels
input_sequences = []
for line in rocket_data:
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

max_sequence_length = max([len(x) for x in input_sequences])
input_sequences = tf.keras.preprocessing.sequence.pad_sequences(input_sequences, maxlen=max_sequence_length, padding='pre')
X, y = input_sequences[:, :-1], input_sequences[:, -1]
y = tf.keras.utils.to_categorical(y, num_classes=total_words)

# Build the model
model = Sequential()
model.add(Embedding(total_words, 50, input_length=max_sequence_length-1))
model.add(LSTM(100, return_sequences=True))
model.add(LSTM(100))
model.add(Dense(total_words, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model (you may want to split this into a separate function if needed)
model.fit(X, y, epochs=20, verbose=2)

# Function to generate text using the trained model
def generate_text(seed_text, next_words, model, max_sequence_length, tokenizer, temperature=1.0):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = tf.keras.preprocessing.sequence.pad_sequences([token_list], maxlen=max_sequence_length-1, padding='pre')
        predicted_probs = model.predict(token_list, verbose=0).flatten()

        # Adjust the temperature to control randomness
        predicted_probs = np.log(predicted_probs) / temperature
        exp_probs = np.exp(predicted_probs)
        predicted_probs = exp_probs / np.sum(exp_probs)

        predicted_index = np.random.choice(len(predicted_probs), p=predicted_probs)
        
        output_word = ""
        for word, index in tokenizer.word_index.items():
            if index == predicted_index:
                output_word = word
                break
        seed_text += " " + output_word
    return seed_text

# Infinite loop to generate text every 20 seconds
while True:
    generated_text = generate_text("Rockets", 20, model, max_sequence_length, tokenizer, temperature=0.2)
    print(generated_text)
    time.sleep(20)  # Sleep for 20 seconds before generating text again